name: validate

on:
  push: {}
  pull_request: {}

jobs:
  main:
    strategy:
      matrix:
        eslint: [5, 6, 7, 8]
        node: [6.14, 6, 8, 10, 12, 14, 16]
        exclude:
          - eslint: 8
            node: 10
          - eslint: 8
            node: 8
          - eslint: 8
            node: 6
          - eslint: 8
            node: 6.14
          - eslint: 7
            node: 8
          - eslint: 7
            node: 6
          - eslint: 7
            node: 6.14
          - eslint: 6
            node: 6
          - eslint: 6
            node: 6.14

    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2

      - name: â” Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ğŸ“¥ Install ESLint
        run: npm install eslint@${{ matrix.eslint }}

      - name: â–¶ï¸ Run tests
        run: npm run test
